name: üöÄ D√©ploiement sur Obambu

on:
  push:
    branches:
      - main # ou master selon ton repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ R√©cup√©ration du code
      - name: üß© Checkout du d√©p√¥t
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Installation et build du projet
      - name: üèóÔ∏è Build du projet Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm i
          mkdir build
          npm run build
          cp -r dist/otaku/browser/* build/

          # ‚úÖ Ajout du .htaccess pour les routes SPA
          cat <<'EOF' > build/.htaccess
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
          </IfModule>
          EOF

      # 3Ô∏è‚É£ D√©ploiement FTP vers Obambu
      - name: üì§ D√©ploiement sur Obambu
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /otaku.gillesngassam.com/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/.cache*
